// Generated by CoffeeScript 1.8.0
(function() {
  var $, bookDue, elem, lendBookList, reservBookList, _i, _len, _ref;

  $ = Sizzle;

  $('#UIPageBody .UIRowContainer:eq(3)>div:has(#mailInfo)')[0].remove();

  bookDue = $('#UIPageBody .UIRowContainer:eq(3)>div:has(#rssReaderList)')[0].cloneNode(true);

  $('#rssReaderList', bookDue)[0].setAttribute('id', 'bookDueList');

  $('.title>span', bookDue)[0].textContent = '図書館 貸出一覧';

  $('#rssList', bookDue)[0].setAttribute('id', 'bookList');

  _ref = $('#bookList>*', bookDue);
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    elem = _ref[_i];
    elem.remove();
  }

  $('#bookList', bookDue)[0].insertBefore(document.createElement('dl'), null);

  $('#UIPageBody .UIRowContainer:eq(3)')[0].insertBefore(bookDue, $('#UIPageBody .UIRowContainer:eq(3)>*:eq(0)')[0]);

  lendBookList = function() {
    var ajax;
    bookDue = $('#UIPageBody .UIRowContainer:eq(3)>div #bookDueList')[0];
    ajax = new XMLHttpRequest();
    ajax.responseType = 'document';
    ajax.addEventListener('load', function() {
      var attr, book, dueList, errorMsg, info, listItem, msg, value, _j, _len1, _ref1, _ref2, _ref3;
      if (this.responseXML.title.match(/(利用者認証|User authentication)/)) {
        errorMsg = document.createElement('dt');
        errorMsg.insertBefore(document.createElement('a'), null);
        $('a', errorMsg)[0].textContent = 'ログインしてください';
        _ref1 = {
          href: 'https://opac.lib.meiji.ac.jp/webopac/asklst.do',
          target: '_blank'
        };
        for (attr in _ref1) {
          value = _ref1[attr];
          $('a', errorMsg)[0].setAttribute(attr, value);
        }
        return $('#bookList>dl', bookDue)[0].insertBefore(errorMsg, null);
      } else {
        dueList = $('.flst_frame:eq(1) tr:not(.flst_head)', this.responseXML);
        if (dueList.length === 0) {
          msg = document.createElement('dt');
          msg.textContent = '現在貸出中の本はありません';
          $('#bookList>dl', bookDue)[0].insertBefore(msg, null);
        } else {
          for (_j = 0, _len1 = dueList.length; _j < _len1; _j++) {
            info = dueList[_j];
            book = {};
            book.id = $('td:nth-child(3) a', info)[0].href.match(/'(.*?)'/)[1];
            book.due = {};
            book.due.date = $('td:nth-child(6)', info)[0].textContent.trim();
            book.due.days = parseInt((new Date(book.due.date) - new Date()) / (24 * 60 * 60 * 1000));
            book.title = $('td:nth-child(7) a', info)[0].textContent.split(' / ')[0];
            listItem = document.createElement('dd');
            listItem.insertBefore(document.createElement('span'), null);
            $('span', listItem)[0].textContent = "" + book.due.date + "（あと" + book.due.days + "日）";
            listItem.insertBefore(document.createElement('a'), null);
            $('a', listItem)[0].textContent = book.title;
            _ref2 = {
              href: "https://opac.lib.meiji.ac.jp/webopac/catdbl.do?pkey=" + book.id + "&initFlg=_RESULT_SET_NOTBIB",
              target: '_blank'
            };
            for (attr in _ref2) {
              value = _ref2[attr];
              $('a', listItem)[0].setAttribute(attr, value);
            }
            $('#bookList>dl', bookDue)[0].insertBefore(listItem, null);
          }
          msg = document.createElement('dt');
          msg.insertBefore(document.createElement('a'), null);
          $('a', msg)[0].textContent = '貸出更新などはこちら';
          _ref3 = {
            href: 'https://opac.lib.meiji.ac.jp/webopac/lenlst.do',
            target: '_blank'
          };
          for (attr in _ref3) {
            value = _ref3[attr];
            $('a', msg)[0].setAttribute(attr, value);
          }
          $('#bookList>dl', bookDue)[0].insertBefore(msg, null);
        }
        return reservBookList();
      }
    });
    ajax.open('GET', 'https://opac.lib.meiji.ac.jp/webopac/lenlst.do');
    return ajax.send(null);
  };

  reservBookList = function() {
    var ajax;
    bookDue = $('#UIPageBody .UIRowContainer:eq(3)>div #bookDueList')[0];
    ajax = new XMLHttpRequest();
    ajax.responseType = 'document';
    ajax.addEventListener('load', function() {
      var attr, book, dueList, info, listItem, msg, value, _j, _len1, _ref1, _results;
      if (!this.responseXML.title.match(/(利用者認証|User authentication)/)) {
        dueList = $('.flst_frame:eq(1) tr:not(.flst_head):has(font)', this.responseXML);
        if (dueList.length !== 0) {
          msg = document.createElement('dt');
          msg.textContent = '予約した本が到着しています';
          $('#bookList>dl', bookDue)[0].insertBefore(msg, null);
          _results = [];
          for (_j = 0, _len1 = dueList.length; _j < _len1; _j++) {
            info = dueList[_j];
            book = {};
            book.href = parseInt($('td:nth-child(9) a', info)[0].href.match(/'(.*?)'/)[1]) + 1;
            book.due = {};
            book.due.date = $('td:nth-child(7)', info)[0].textContent.trim();
            book.due.days = parseInt((new Date(book.due.date) - new Date()) / (24 * 60 * 60 * 1000));
            book.title = $('td:nth-child(9) a', info)[0].textContent.split(' / ')[0];
            listItem = document.createElement('dd');
            listItem.insertBefore(document.createElement('span'), null);
            $('span', listItem)[0].textContent = "" + book.due.date + "（あと" + book.due.days + "日）";
            listItem.insertBefore(document.createElement('a'), null);
            $('a', listItem)[0].textContent = book.title;
            _ref1 = {
              href: "https://opac.lib.meiji.ac.jp/webopac/rsvdtl.do?startpos=1&hitcnt=1&sortkey=limdt%2FASC&listcnt=100&listpos=" + book.href,
              target: '_blank'
            };
            for (attr in _ref1) {
              value = _ref1[attr];
              $('a', listItem)[0].setAttribute(attr, value);
            }
            _results.push($('#bookList>dl', bookDue)[0].insertBefore(listItem, null));
          }
          return _results;
        }
      }
    });
    ajax.open('POST', 'https://opac.lib.meiji.ac.jp/webopac/rsvlst.do');
    ajax.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
    return ajax.send('sortkey=limdt%2FASC&listcnt=100');
  };

  lendBookList();

}).call(this);
