// Generated by CoffeeScript 1.8.0
(function() {
  var $, $$, $x, xhr;

  $ = function(selector, parentElement) {
    return (parentElement || document).querySelector(selector);
  };

  $$ = function(selector, parentElement) {
    var array, i, nodes, _i, _ref;
    nodes = (parentElement || document).querySelectorAll(selector);
    array = [];
    for (i = _i = 0, _ref = nodes.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
      array.push(nodes[i]);
    }
    return array;
  };

  $x = function(expression, parentElement) {
    var array, i, xpaths, _i, _ref;
    array = [];
    xpaths = document.evaluate(expression, parentElement || document, null, XPathResult.ORDERED_NODE_SNAPSHOT_TYPE, null);
    for (i = _i = 0, _ref = xpaths.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
      array.push(xpaths[i]);
    }
    return array;
  };

  $.create = function(tagName) {
    return document.createElement(tagName);
  };

  xhr = new XMLHttpRequest();

  xhr.onload = function() {
    var important, infoBar;
    important = $('.importantNews a', this.responseXML);
    if (!(important != null)) {
      return;
    }
    infoBar = $('#pageHeaderBlock > p, #pageHeaderBlock > div.logininfo');
    infoBar.style.textAlign = 'left';
    infoBar.style.fontSize = '125%';
    infoBar.innerHTML = '';
    important = document.importNode(important, true);
    important.style.color = 'red';
    important.href = "https://www.meiji.ac.jp/" + important.getAttribute('href');
    important.setAttribute('target', '_blank');
    return infoBar.appendChild(important);
  };

  xhr.open("GET", "https://www.meiji.ac.jp/");

  xhr.responseType = "document";

  xhr.send();

}).call(this);
